#!/bin/sh

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh

#BSPWM configuration
bspc config focused_border_color  '#D8DEE9'
bspc config normal_border_color  '#2E3440'
bspc config border_width         1
bspc config window_gap           15
bspc config split_ratio          0.52
bspc config focus_follows_pointer true
bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#Single monitor
bspc monitor -d 1 2 3 4

#Floating applications
bspc rule -a Galculator state=floating
bspc rule -a Pavucontrol state=floating
